### PR TITLE
Code style fixes

### PR DESCRIPTION
**Pull request by samrocketman**
Similar to my style fixes on your other PR @alextd.

### CODE REVIEW

**Comment by samrocketman** [comment]
The CI failures mean you need to update with upstream master.  I could if you want but kept the changes to minimum here for code style.

**Comment by warp-core** [comment]
@samrocketman I'm looking to re-PR @alextd's PR since they've been away for a while. I've merged this change into the updated branch.

**Comment by samrocketman** [comment]
sounds good

**Comment by alextd** [comment]
Yah I've been busy and things keep delaying me from looking at these, so please take it from me and cross that off my todolist

**Pull request closed without merging**
